print('hello, world💕')
print('meu texto aqui')
print('o que é isso')
print('sai daqui garoto')
print('eu sou linda')
print('a mentira tem perna curta')
print('não sei o que de não sei o que lá')
print('mas ele disse isso e mais um pouco')
print('e o que eu tenho haver com isso?')
print('meta de vida, ser vekha fofoqueira')